name: Data PipelineTest CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository PipelineTest
      uses: actions/checkout@v3

    - name: Set up PythonVersion
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install dependenciesTestPipeline
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt
        
    - name: Run testPipelineData
      run: |
        chmod +x project/tests.sh
        project/tests.sh
